version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 4

  - package-ecosystem: "npm"
    directory: "/services/idp"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 4
    cooldown:
      default-days: 1
